name: run android tests

on: push

jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: pull the project into the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium
          appium -v
          appium &>/dev/null &
          appium driver install uiautomator2
          appium driver list --installed

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test -Pandroid
